#!/usr/bin/env python3
"""Write the one stylesheet every ERA v2 page links.

Every page used to inline ~35KB of identical CSS (630KB across 18 pages, none of it
cacheable between navigations). This concatenates the same pieces, in the same order,
into staging/v2/era.css so the browser fetches it once.

Order matters — later rules win, exactly as when they were inlined:
    V2.CSS  ->  P.EXTRA  ->  SEO.CHROME_CSS  ->  S.SVC_CSS  ->  R.RS_CSS  ->  P.CSS_404

find-your-spain keeps its own page-specific <style>; it is unique to that page.
"""
import os, sys, io

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import era_seo as SEO
import gen_era_v2 as V2
import gen_era_pages as P
import gen_era_services as S
import gen_era_reskin as R


def stylesheet():
    return "".join([
        "/* Spanish AfterLife — ERA v2. Generated by staging-src/build_css.py; do not edit. */\n",
        V2.CSS, P.EXTRA, SEO.CHROME_CSS, S.SVC_CSS, R.RS_CSS, P.CSS_404,
    ])


def write(out_dir):
    css = stylesheet()
    p = os.path.join(out_dir, "era.css")
    os.makedirs(out_dir, exist_ok=True)
    io.open(p, "w", encoding="utf-8").write(css)
    return p, len(css)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(HERE), "staging", "v2")
    p, n = write(target)
    print(f"wrote {p} ({n/1024:.1f} KB)")
