#!/usr/bin/env python3
"""Write the one stylesheet every ERA v2 page links.

Every page used to inline ~35KB of identical CSS (630KB across 18 pages, none of it
cacheable between navigations). This concatenates the same pieces, in the same order,
into staging/v2/era.css so the browser fetches it once.

Order matters — later rules win, exactly as when they were inlined:
    V2.CSS  ->  P.EXTRA  ->  SEO.CHROME_CSS  ->  S.SVC_CSS  ->  R.RS_CSS  ->  P.CSS_404

find-your-spain keeps its own page-specific <style>; it is unique to that page.
"""
import os, sys, io

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import era_seo as SEO
import gen_era_v2 as V2
import gen_era_pages as P
import gen_era_services as S
import gen_era_reskin as R


def stylesheet():
    return "".join([
        "/* Spanish AfterLife — ERA v2. Generated by staging-src/build_css.py; do not edit. */\n",
        V2.CSS, P.EXTRA, SEO.CHROME_CSS, S.SVC_CSS, R.RS_CSS, P.CSS_404,
        MOBILE_FLOOR,
    ])


# Must be LAST. Media queries add no specificity, so a mobile override placed in an
# earlier block loses to any later base rule with the same selector weight.
MOBILE_FLOOR = """
@media(max-width:900px){
 /* One 12px floor for every uppercase micro-label. Letter-spaced caps below that
    stop being legible on a phone, and the earlier per-selector values had drifted
    as low as 10.24px (footer headings, the subhero chips). Measured on the live
    site at 375px: .chip span and .foot-col h2 at 10.24, .ptable th at 10.88. */
 .ovl,
 .svc-card .tag,.svc-card404 .tag,.art-meta,.coll-meta,.nk,.card-note,.sw-c-idx,.place-tag,.srow-fee,.micro,
 .ptable th,.inc h3,.pillar h3,
 .chip span,.foot-col h2,.foot-bot,.foot-bot span,.foot-bot a,
 .gbtn,.lm-submit{font-size:.75rem}
 /* 13x13 is not a tap target; the label row around it already gives 44px of height */
 input[type=checkbox]{width:20px;height:20px;flex:0 0 20px}
}"""


def write(out_dir):
    css = stylesheet()
    p = os.path.join(out_dir, "era.css")
    os.makedirs(out_dir, exist_ok=True)
    io.open(p, "w", encoding="utf-8").write(css)
    return p, len(css)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(HERE), "staging", "v2")
    p, n = write(target)
    print(f"wrote {p} ({n/1024:.1f} KB)")
